[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "JvUHHza3Wc"
weight = 9_999

[[footer]]
pre = "codeberg"
name = "About"
pageRef = "about"
identifier = "JvUHHza3Wx"
weight = 1
